# services we want
services:
  mongodb:
    # get the latest version of mongodb
    image: mongo:latest
    container_name: coffee_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # always up unless stopped
    restart: unless-stopped

  redis:
    # get the lite version of redis
    image: redis:alpine
    container_name: coffee_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # always up unless stopped
    restart: unless-stopped
    
  backend:
    build: ./CMSERVER
    container_name: cm_backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/coffee_machine 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PASS=1234 
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./CMSERVER:/app             
      - /app/node_modules          
    command: npm run dev            

  frontend:
    build: ./CMCLIENT
    container_name: cm_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
     - ./CMCLIENT:/app 
     - /app/node_modules
          
# after the define, now we run it
volumes:
  mongo_data:
  redis_data: